/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/chat': RouteRecordInfo<
      '/chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main': RouteRecordInfo<
      '/main',
      '/main',
      Record<never, never>,
      Record<never, never>,
      | '/main/'
      | '/main/settings'
      | '/main/statistics'
    >,
    '/main/': RouteRecordInfo<
      '/main/',
      '/main',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/settings': RouteRecordInfo<
      '/main/settings',
      '/main/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/main/statistics': RouteRecordInfo<
      '/main/statistics',
      '/main/statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/toolbar': RouteRecordInfo<
      '/toolbar',
      '/toolbar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/chat.vue': {
      routes:
        | '/chat'
      views:
        | never
    }
    'src/pages/main.vue': {
      routes:
        | '/main'
        | '/main/'
        | '/main/settings'
        | '/main/statistics'
      views:
        | 'default'
    }
    'src/pages/main/index.vue': {
      routes:
        | '/main/'
      views:
        | never
    }
    'src/pages/main/settings.vue': {
      routes:
        | '/main/settings'
      views:
        | never
    }
    'src/pages/main/statistics.vue': {
      routes:
        | '/main/statistics'
      views:
        | never
    }
    'src/pages/toolbar.vue': {
      routes:
        | '/toolbar'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
